#framework_publish_github:
 # script:
  #  - git clone -b add-sync-gitlab-tags-with-github-script https://gitlab-ci-token:${CI_JOB_TOKEN}@lab.jamit.de/pace/mobile/common.git tmp/common
   # - pip3 install -r tmp/common/scripts/screenshots/requirements.txt
    #- echo "$GITLAB_API_TOKEN"
    #- python3 tmp/common/scripts/tags/create_github_release.py -d telip007/CI-Release-Test 
  #tags:
  #  - xcode-12.4
  # only:
  #  - tags