# Create GitHub release
framework_publish_github:
  script:
    - 'curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token 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" "https://api.github.com/repos/telip007/CI-Release-Test/releases" -d "{"tag_name":"$CI_COMMIT_REF_NAME"}"'
  only:
    - tags